# Generated by Django 2.2 on 2019-04-20 09:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190419_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/static/img'), upload_to=''),
        ),
    ]
